<?php
// Copyright 1999-2017. Plesk International GmbH. All rights reserved.
?>
<div class="social-actions">
    <a class="fb-link" href="<?php echo $this->escape($this->href); ?>" target="_blank">
        <svg class="icon" id="facebook" viewBox="0 0 32 32">
            <path d="M17.906,9.9V7.012a1.662,1.662,0,0,1,1.776-1.546h3.094V-0.052l-4.26-.022c-4.736,0-5.579,4.113-5.579,6.746L13,9.9H9.97v6.123h2.96v16.1H17.9v-16.1h4.447l0.2-2.53,0.3-3.593H17.906"></path>
        </svg>
        <?php echo lmsg('facebook_join_community'); ?>
    </a>
</div>
