<?php
/**
* WARNING - IF YOU ARE NOT HIGHLY PROFICIENT WITH REGULAR EXPRESSIONS, DO NOT TOUCH THIS FILE.
*
* If you decide to modify this file, CREATE A BACKUP FIRST.
*
* Please read the README.TXT in this directory.
*/

$GLOBALS['Spam_Rules']['spamassassin'] = array(
	'headers' => array (
		array('/\\bc.{0,2}i.{0,2}a.{0,2}l.{0,2}i.{0,2}s\\b/i', 'Subject contains a gappy version of \'cialis\'', 0.003),
		array('/l.{0,2}e.{0,2}v.{0,2}i.{0,2}t.{0,2}r.{0,2}a/i', 'Subject contains a gappy version of \'levitra\'', 2.515),
		array('/\\bs.{0,1}o.{0,1}m.{0,1}a\\b/i', 'Subject contains a gappy version of \'soma\'', 0),
		array('/v.{0,2}a.{0,2}l.{0,2}i.{0,2}u.{0,2}m/i', 'Subject contains a gappy version of \'valium\'', 1.014),
		array('/x.{0,2}a.{0,2}n.{0,2}a.{0,2}x/i', 'Subject contains a gappy version of \'xanax\'', 1.766),
		array('/[s5][e3\\xE8-\\xEB]x[u\\xB5\\xF9-\\xFC][a4\\xE0-\\xE6@][l!|1](?:[l!|1]y)?.{0,3}[e3\\xE8-\\xEB]xp[l!|1][i1!|l\\xEC-\\xEF]c[i1!|l\\xEC-\\xEF]t/i', 'Subject indicates sexually-explicit content', 0.001),
		array('/^Re: new\\s?\\d{0,3}$/i', 'Subject is Re: new \\d\\d\\d', 2.687),
		array('/\\bat no cost/i', 'Subject says \"At No Cost\"', 1.561),
		array('/CHEAP/', 'Phrase: Cheap in Caps in Subject.', 0.001),
		array('/\\$\\d\\d\\d?\\.?\\d?\\d? bonus/i', 'Subject talks about money bonus!', 2.673),
		array('/ejaculat(?:[io01][o0i1]n|e)/i', 'Phrase: ejaculation in subject.', 1.803),
		array('/ erection /i', 'Phrase: erection in subject.', 2.643),
		array('/(?:huge|tiny|small) (?:c[o0]ck|d[i1]ck|p[e3]n[1i]s)/i', 'Phrase: Huge Cock', 0),
		array('/(?!100%)\\d[0-9oi][0-9oi]%/i', 'Larger than 100% in subj.', 0.412),
		array('/ low rates/i', 'Subject says low rates', 2.001),
		array('/^New software uploaded by/', 'Subj starts with New software uploaded', 1.790),
		array('/^Re: news? [a-z]{1,5}$/', 'Subject looks like Fharmacy spams.', 1.100),
		array('/n[o0O] p[reRE][erER]scr[i1I]pt[i1I][o0O]n/i', 'Subject almost says No prescription', 1.577),
		array('/\\b(?!(?:pharmacy|primacy))p[ph]{0,4}\\S{1,3}r\\S{0,2}m\\S{0,3}c\\S{0,2}y\\b/i', 'what could this word be?', 1.460),
		array('/perscr[i1]pt[i1][o0]n/i', 'Subject mis-spelled prescription', 0),
		array('/PH[A-Za-z]{2,7}MA/', 'Looks like Phramacy subject.', 3.896),
		array('/ramrod/i', 'Subject says Ramrod', 2.777),
		array('/replica/i', 'Subject says \"replica\"', 1.041),
		array('/replica watch/i', 'Subject says Replica watch', 2.502),
		array('/re approved/i', 'Phrase: re approved', 0),
		array('/^Do you (?:dream|have|want|love|like|wanna)/i', 'Subject starts with Do you dream,have,want,love, etc.', 3.097),
		array('/^Lose /i', 'Subject starts with Lose', 2.167),
		array('/teen.{1,15}(?:pussy|sex|slut|ass|fuck|rape)/i', 'Subject says something bad about teens', 2.549),
		array('/(?:tip|good) \\d\\d\\d?\\d?/i', 'Phrase: subject = tip ddd', 0.101),
		array('/will help/', 'Subject says will help', 3.296),
		array('/with (?:\\w+\\s)?(?:small|short)/i', 'Subject says With ... small', 0),
		array('/^New software uploaded by/', 'Subject starts with \'New software uploaded by\'', 3.599),
		array('/\\bOnline Pharmaceutical/i', 'Subject contains the phrase \'Online pharmaceutical\'', 0.001),
		array('/\\b[a-zA-Z]+ [\\#\\s]{1,4}\\d+[A-Z]+/', 'Subject has spammy looking monetary reference', 0),
	),
	'body' => array (
		array('/\\b(?:CIALIS|LEVITRA|VIAGRA)/', 'Mentions an E.D. drug', 0.322),
		array('/\\bsildenafil\\b/i', 'Talks about an E.D. drug using its chemical name', 1.185),
		array('/\\bGeneric Viagra\\b/', 'Mentions Generic Viagra', 1.558),
		array('/\\bviagra .{0,25}(?:express|online|overnight)/i', 'Fast Viagra Delivery', 0),
		array('/\\bonline pharmacy|\\b(?:drugs|medications) online/i', 'Online Pharmacy', 0.001),
		array('/no.{1,10}P(?:er|re)scription.{1,10}(?:needed|require|necessary)/i', 'No prescription needed', 2.619),
		array('/\\bvia.gra\\b/i', 'Attempts to disguise the word \'viagra\'', 0.133),
		array('/(?:Viagra|Valium|Xanax|Soma|Cialis){2}/i', 'Two or more drugs crammed together into one word', 0),
		array('/100% GUARANTEED/i', 'One hundred percent guaranteed', 0.012),
		array('/^\\s*Dear Friend\\b/i', 'Dear Friend? That\'s not very dear!', 2.699),
		array('/\\bDear (?:IT\\W|Internet|candidate|sirs?|madam|investor|travell?er|car shopper|web)\\b/i', 'Contains \'Dear (something)\'', 1.605),
		array('/[BM]ILLION DOLLAR/', 'Talks about lots of money', 1.875),
		array('/To Be Removed,? Please/i', 'Claims you can be removed from the list', 1.336),
		array('/you(?:\'ve|\'re| have| are)? receiv(?:e|ed|ing) this (?:advertisement|offer|special|recurring|paid).{0,16}\\b(?:by either|because)/i', 'Claims you wanted this ad', 2.596),
		array('/to be removed from.{0,20}(?:mailings|offers)/i', 'Talks about how to be removed from mailings', 0.001),
		array('/strong buy/i', 'Tells you about a strong buy', 2.488),
		array('/\\bstock alert/i', 'Offers a alert about a stock', 2.897),
		array('/not a registered investment advisor/i', 'Not registered investment advisor', 0),
		array('/prestigi?ous\\b.{0,20}\\bnon-accredited\\b.{0,20}\\buniversities/i', '\'Prestigious Non-Accredited Universities\'', 0),
		array('/\\b(?:enlarge|increase|grow|lengthen|larger\\b|bigger\\b|longer\\b|thicker\\b|\\binches\\b).{0,50}\\b(?:penis|male organ|pee[ -]?pee|dick|sc?hlong|wh?anger|breast(?!\\s+cancer))/i', 'Information on growing body parts', 0.309),
		array('/\\b(?:penis|male organ|pee[ -]?pee|dick|sc?hlong|wh?anger|breast(?!\\s+cancer)).{0,50}\\b(?:enlarge|increase|grow|lengthen|larger\\b|bigger\\b|longer\\b|thicker\\b|\\binches\\b|size)/i', 'Information on getting larger body parts', 0.001),
		array('/\\b(?:impotence (?:problem|cure|solution)|Premature Ejaculation|erectile dysfunction)/i', 'Impotence cure', 1.886),
		array('/\\b(?:\\d{1,3})?Million\\b.{0,40}\\b(?:Canadian Dollar?s?|US\\$|U\\.? ?S\\.? Dollar)/i', 'Talks about a million North American dollars', 1.329),
		array('/(?:\\$|usd).?\\d{1,3}[,.]\\d{3}[,.]\\d{3}(?:[,.]\\d\\d)?/i', 'Mentions millions of $ ($NN,NNN,NNN.NN)', 0.630),
		array('/Million\\b.{0,40}\\b(?:United States? Dollars?|USD)/i', 'Talks about millions of dollars', 1.528),
		array('/urgent.{0,16}(?:assistance|business|buy|confidential|notice|proposal|reply|request|response)/i', 'Contains urgent matter', 1.585),
		array('/money back guarantee/i', 'Money back guarantee', 0.001),
		array('/free.{0,12}(?:(?:instant|express|online|no.?obligation).{0,4})+.{0,32}\\bquote/i', 'Free express or no-obligation quote', 1.496),
		array('/\\b(?:bad|poor|no\\b|eliminate|repair|(?:re)?establish|damag).{0,10} (?:credit|debt)\\b/i', 'Eliminate Bad Credit', 0.001),
		array('/\\brefinance your(?: current)? (?:home|house)\\b/i', 'Home refinancing', 2.039),
		array('/time to refinance|refinanc\\w{1,3}\\b.{0,16}\\bnow\\b/i', 'Home refinancing', 0.556),
		array('/\\bno medical exam/i', 'No Medical Exams', 0),
		array('/\\b(?:(?:without|no) (?:exercis(?:e(?! price)|ing)|dieting)|weight.?loss|(?:extra|lose|lost|losing).{0,10}(?:pounds|weight|inches|lbs)|burn.{1,10}fat)\\b/i', 'Lose Weight Spam', 0.083),
		array('/\\bfinancial(?:ly)? free/i', 'Freedom of a financial nature', 2.596),
		array('/\\bcontains forward-looking statements\\b/i', 'Stock Disclaimer Statement', 0),
		array('/\\bone\\W+time (?:charge|investment|offer|promotion)/i', 'One Time Rip Off', 0),
		array('/\\bjoin (?:millions|thousands)\\b/i', 'Join Millions of Americans', 1.777),
		array('/\\b(?:marketing|network) partner|\\bpartner (?:web)?site/i', 'Claims you registered with a partner', 1.295),
		array('/\\blow.{0,4} (?-i:P)rice/i', 'Lowest Price', 0.001),
		array('/\\bunclaimed (?:funds|money|prizes?|rewards?)\\b/i', 'People just leave money laying around', 3.096),
		array('/\\w+\\^\\S+\\(\\w{2,4}\\b/', 'Message seems to contain rot13ed address', 0.001),
		array('/\\boprah!/i', 'Talks about Oprah with an exclamation!', 0),
		array('/A(?i:ct) N(?i:ow)/', 'Talks about \'acting now\' with capitals', 0.792),
		array('/increased?.{0,9}(?:sex|stamina)/i', 'Talks about a bigger drive for sex', 1.183),
		array('/\\bguaranteed?\\!/i', 'Something is emphatically guaranteed', 0.939),
		array('/\\binvestment advice/i', 'Message mentions investment advice', 0.042),
		array('/male enhancement/i', 'Message talks about enhancing men', 2.596),
		array('/\\baffordable .{0,10}prices\\b/i', 'Message says that prices aren\'t too expensive', 0.001),
		array('/\\breplica.{1,20}rolex/i', 'Message talks about a replica watch', 3.396),
		array('/[^\\s\\w.]rolex/i', 'Message puts emphasis on the watch manufacturer', 0),
		array('/\\bfree (?:porn|xxx|adult)/i', 'Possible porn - Free Porn', 0),
		array('/\\bcum[ -]?shots?\\b/i', 'Possible porn - Cum Shot', 2.799),
		array('/\\blive .{0,9}(?:fuck(?:ing)?|sex|naked|girls?|virgins?|teens?|porno?)\\b/i', 'Possible porn - Live Porn', 0),
		array('/banking laws/i', 'Talks about banking laws', 2.002),
		array('/(?:add|gain) inches/i', 'Add / Gain inches', 2.131),
		array('/\\b[b-z]sex+\\b/i', 'It\'s almost sex, but not!', 2.110),
		array('/Ana[^a-z]trim/i', 'Broken AnaTrim phrase.', 3.764),
		array('/A[-_\\.]U[-_\\.]N[-_\\.]I/i', 'Phrase: A_U_N_I', 0.823),
		array('/[BM][I1]LL[I1]0N/i', 'Phrase: [BM]Illi0n', 0),
		array('/c0mpany/i', 'Phrase: C0mpany', 2.455),
		array('/can last longer/i', 'Phrase: can last longer', 0.442),
		array('/(?!CIALIS)C\\s?[a-z]?\\s?[Iitl1\\\\\\/]\\s?[a-z]?\\s?[Aa]\\s?[a-z]?\\s?[LIl1\\\\\\/]\\s?[a-z]?\\s?[ilIt1\\\\\\/]\\s?[a-z]?\\s?[Ss]/', 'Uses a mis-spelled version of cialis.', 1.441),
		array('/\\b[a-z]{1,5}0[a-z]{3,9}\\s[a-z]{1,5}0[a-z]{3,9}\\b/i', 'Looks like double 0 words', 3.533),
		array('/email hier/i', 'Phrase: email hier', 2.189),
		array('/extra inches/', 'Phrase: extra inches', 2.442),
		array('/\\$\\d\\d?O\\s*[MBT]/i', 'Looks like numbers with O\'s insted of 0\'s', 0),
		array('/(?:\\b|\\b\\d)\\d,?\\d,?OO(?:\\b|\\d\\b)/', 'Looks like fake numbers (4)', 0),
		array('/Fharmacy/i', 'Phrase: Farmacy', 3.576),
		array('/(?!forward look)f[o0]rward l[0o][0o]k/i', 'Phrase: forward look with 0\'s', 1.000),
		array('/(?:[a-z] ){8}, (?:[a-z0-9] ){4}/i', 'Too much spacing in Address', 2.674),
		array('/(?:place f[o0]r|[0o]rder|get\\s?(?:y[o0]ur)?|online|quality).{1,7}med[isz][^a]/i', 'Looks like trying to sell meds', 0.803),
		array('/(?:pef-rx|vigrex-ds|gsc-100|vp-rx|gv-promax|phentermine|adipex|xenical)/i', 'Looks like generic viagra', 0.127),
		array('/Hey bro, /', 'Phrase hey bro,', 2.331),
		array('/\\bHGH\\b/', 'Phrase: HGH', 0.274),
		array('/\\$\\d{3},\\d{3} home loan/i', 'Phrase $x home loan', 0.710),
		array('/\\bimpress .{0,5}girl\\b/', 'Phrase: impress ... girl', 2.581),
		array('/Increase your energy/i', 'Phrase: Increase your energy', 3.396),
		array('/independent reward/i', 'Phrase: independent reward', 3.595),
		array('/\\bl0ans?\\b/i', 'Phrase: L0an', 0),
		array('/-- [a-z]{21}/', 'Special people leave special signs!', 3.995),
		array('/lower your monthly payments/i', 'Phrase: lower your monthly payments', 2.996),
		array('/\\bmore size\\b/', 'Phrase: more size', 0.397),
		array('/(?!\\d{3})8(?:66|77|88|[0o][0o])[-\\.\\s\\)]{1,3}[OIL0-9]{3}[-\\.\\s]/i', 'Looks like a fake phone number (1)', 2.596),
		array('/8(?:66|77|88|[0o][0o])[-\\.\\s\\)]{1,3}[OIL0-9]{3}[-\\.\\s]{1,3}(?!\\d{4})[OIL0-9]{4}/i', 'Looks like a fake phone number (3)', 2.599),
		array('/(?!school)[\\$s5]ch[o0][o0][il1\\|]/i', 'Looks like school but it\'s not!', 2.961),
		array('/No.{1,10}P(?:er|re)scr[i1]pt[i1][o0]n (?:needed|requ[1i]re)/i', 'Phrase: no prescription needed.', 3.228),
		array('/1[0-9][\\s\\.]?y[\\s\\.]?o[\\s\\.]?\\b/i', 'Speaks of teenager.', 2.397),
		array('/2[0-9][\\s\\.]?y[\\s\\.]?o[\\s\\.]?\\b/i', 'Speaks of 20+ year old.', 0),
		array('/\\$\\d\\s,\\s\\d\\d/', 'Looks like money but has odd spacing.', 1.959),
		array('/oniine/i', 'Mis-spelled online', 0),
		array('/\\bp1ll/i', 'Phrase: p1ll', 1.814),
		array('/pen[i1]s grow(?:th)?/i', 'Phrase: penis growth', 0),
		array('/(?!dollar)d[o0][1|li][1|li]ar/i', 'Phrase: Dollar, with pipes or 0\'s.', 2.599),
		array('/(?!illion)i[l|][l|][i|][o0]n/i', 'Looks like illion, but it\'s not', 0),
		array('/(?:prolonged|increased) hardness/i', 'Talks about prolonged hardness', 0),
		array('/quality replica/i', 'Phrase: quality replica', 2.949),
		array('/r e f c o d e/i', 'Refcode with spacing', 3.599),
		array('/REPLICAS?\\b/', 'Phrase: REPLICA', 3.242),
		array('/\\bre[^a-z]fi\\b/', 'Looks like refi.', 2.696),
		array('/Roller is th/i', 'Phrase: Roller is th', 0),
		array('/\\brolx\\b/i', 'Phrase: rolx', 1.000),
		array('/\\bsoft\\s?t?abs\\b/i', 'Phrase: Softabs', 3.513),
		array('/F R E E/i', 'Phrase: F R E E', 0),
		array('/\\d\\d\\d--\\d\\d\\d--?\\d\\d\\d\\d/', 'Phone number with -- spacing. (B)', 2.896),
		array('/\\s\\d\\s\\d\\s\\d\\s\\d\\s\\d\\s-\\s\\d\\s\\d\\s\\d\\s\\d/', 'Looks like a  s p a c e d zipcode.', 1.680),
		array('/\\bSPUR-M\\b/i', 'Phrase: SPUR-M', 0),
		array('/\\bssex\\b/', 'Phrase: ssex', 2.489),
		array('/st[0o]ck\\b.{4,10}expl[o0]de/i', 'Looks like stocks exploding.', 1.833),
		array('/\\bSymblo\\b/i', 'Mis-spelled symbol.', 0),
		array('/this advertiser/i', 'Phrase: this advertiser', 0),
		array('/thousand personal/i', 'Phrase: thousand personal', 1.000),
		array('/To (?:(?:stop further|longer get) distribution|stop (?:receiving )?announcements)/i', 'Phrase: to stop further distribution', 3.096),
		array('/Ultra Allure/i', 'Phrase: Ultra Allure', 2.999),
		array('/lock ?(?:to ?)? your girlfriend/i', 'Phrase: lock to your girlfriend', 2.002),
		array('/\\{PROV_\\d_\\d\\}/', 'Pattern Replacement PROV_D', 0.765),
		array('/yourself master/i', 'Phrase: yourself master', 2.011),
		array('/Your refi/i', 'Phrase: Your refi', 3.518),
		array('/<inter W0><post P2>\\b(?!adobe)<A><D><O><B><E>\\b/i', 'ReplaceTags: Adobe', 0),
		array('/<inter SP2><post P2>(?:<B><I><G><G><E><R>|<L><A><R><G><E><R>).{1,8}(?:<P><E><N><I><S>|<B><R><E><A><S><T>|<M><E><M><B><E><R>)/i', 'ReplaceTags: Bigger / Larger, Penis / Member', 1.782),
		array('/<inter SP2><post P2>\\b(?!diploma)<D><I><P><L><O><M><A>/i', 'ReplaceTags: Diploma', 0),
		array('/<inter SP2><post P2>\\b(?!discount)<D><I><S><C><O><U><N><T>/i', 'ReplaceTags: Discount', 1.810),
		array('/<inter SP2><post P2>\\b(?!dollar)<D><O><L><L><A><R>/i', 'ReplaceTags: Dollar', 2.366),
		array('/<inter W0><post P2>\\b(?!estabi?lish)<E><S><T><A><B><L><I><S><H>/i', 'ReplaceTags: Establish (2)', 0),
		array('/<inter W0><post P2>\\b(?!fuck)<F><U><C><K>/i', 'ReplaceTags: Fuck (2)', 0),
		array('/<inter SP2><post P2>(?!guarantee)<G><U><A><R><A><N><T><E><E>/i', 'ReplaceTags: Guarantee (1)', 1.253),
		array('/<inter SP2><post P2>\\b(?!investor)<I><N><V><E><S><T><O><R>/i', 'ReplaceTags: Investor', 0),
		array('/<inter W0><post P2>(?!levitra)<L><E><V><I><T><R><A>/i', 'ReplaceTags: Levitra', 1.814),
		array('/<inter SP2><post P2>\\b(?!meeting)<M><E><E><T><I><N><G>\\b/i', 'ReplaceTags: Meeting', 2.699),
		array('/<inter W0><post P2>\\b(?!offer)<O><F><F><E><R>/i', 'ReplaceTags: Offer (2)', 1.287),
		array('/<inter W0><post P2>(?!opportun)<O><P><P><O><R><T><U><N>/i', 'ReplaceTags: Oppertun (2)', 2.689),
		array('/<inter SP2><post P2>\\b(?!pen\\s?is)(?!penny[ \']?s)<P><E><N><I><S>/i', 'ReplaceTags: Penis', 2.486),
		array('/<inter SP2><post P2>\\b(?!price)<P><R><I><C><E>\\b/i', 'ReplaceTags: Price', 3.491),
		array('/<inter SP2><post P2>\\b(?!refinanc)<R><E><F><I><N><A><N><C>/i', 'ReplaceTags: Refinance (1)', 0.921),
		array('/<inter SP2><post P2>\\b(?!rolex)<R><O><L><E><X>/i', 'ReplaceTags: Rolex', 3.096),
		array('/<inter SP2><post P2>\\b(?!sexual)<S><E><X><U><A><L>/i', 'ReplaceTags: Sexual', 3.142),
		array('/<post P2>\\b(?!soma|500mg)<S><O><M><A>\\b/i', 'ReplaceTags: Soma', 0),
		array('/<inter SP2><post P2>\\b(?!soma|500? ?mg)<S><O><M><A>\\b/i', 'ReplaceTags: Soma (2)', 0),
		array('/<inter SP2><post P2>\\b(?!stro\\s?ng)<S><T><R><O><N><G>\\b/i', 'ReplaceTags: Strong (1)', 2.976),
		array('/<inter W0><post P2>\\b(?!strong)<S><T><R><O><N><G>\\b/i', 'ReplaceTags: Strong (2)', 3.096),
		array('/<inter SP2><post P2>\\b(?!symbol)<S><Y><M><B><O><L>/i', 'ReplaceTags: Symbol', 2.943),
		array('/<inter W0><post P2>\\b(?!today)<T><O><D><A><Y>/i', 'ReplaceTags: Today (2)', 2.382),
		array('/<inter W0><post P2>\\b(?!valium)<V><A><L><I><U><M>/i', 'ReplaceTags: Valium', 1.590),
		array('/<inter SP2><post P2>\\b(?!valium)<V><A><L><I><U><M>/i', 'ReplaceTags: Valium (2)', 1.301),
		array('/<inter W0><post P2>\\b(?!weight)<W><E><I><G><H><T>/i', 'ReplaceTags: Weight (2)', 2.121),
		array('/<inter W0><post P2>\\b(?!xanax)<X><A><N><A><X>\\b/i', 'ReplaceTags: Xanax (1)', 2.423),
		array('/<inter SP2><post P2>\\b(?!xanax)<X><A><N><A><X>\\b/i', 'ReplaceTags: Xanax (2)', 0.001),
		array('/^\\w+ has uploaded some new software/', 'Somebody has uploaded some new software for you', 2.658),
		array('/loop-?hole in the banking/i', 'A loop hole in the banking laws?', 2.210),
		array('/\\byour .{0,40}account .{0,40}record/i', 'Message has a phrase standard for phishing mails', 2.996),
		array('/\\byour .{0,40}account .{0,40}security/i', 'Message has a phrase standard for phishing mails', 0),
	),
);
